DROP DATABASE IF EXISTS db_jpa;
CREATE DATABASE IF NOT EXISTS db_jpa;

USE DB_JPA;

CREATE TABLE IF NOT EXISTS CUSTOMERS(
    ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    SURNAME VARCHAR(255),
    BIRTDATE VARCHAR(255),
    PHONE VARCHAR(50),
    COUNTRY VARCHAR(50),
    CITY VARCHAR(50),
    DIRECTION VARCHAR(50),
    POSTCODE VARCHAR(50)
);

INSERT INTO CUSTOMERS (NAME, SURNAME, BIRTDATE, PHONE, COUNTRY, CITY, DIRECTION, POSTCODE) VALUES 
('Jorge', 'Lorenzo', '1991/02/13', '66666666', 'SPAIN', 'Girona', 'Calle Girona', '1234'),
('Marc', 'Marquéz', '1989/01/22', '66666666', 'SPAIN', 'Barcelona', 'Calle Barcelona 12 1º Esc D.', '1234');
SELECT * FROM CUSTOMERS;