version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "Naramsim"
    groups:
       dependencies:
          patterns:
            - "*"
    versioning-strategy: increase
